class ru_RU:
	firstMessageText = "Привет чач!"
	helpCommandsText = "Список доступных команд: \n\n"
	helpNoCommandsText = "Нет команд, добавьте первую с помощью /addcom <команда> <текст>"
	commandNewText = "Добавлена команда !"
	commandRemoveText = "Удалена команда !"
	promoteToAdminText = "Повышен до Админа"
	promoteToUserText = "Понижен до Пользователя"

	aboutUserText = """<b>Информация об участнике</b> {0}\n<b>ID:</b> <code>{1}</code>\n<b>Всего сообщений:</b> {2}\n<b>Предупреждения:</b> {3}/{4}"""
	langChange = "Язык успешно изменён на Русский"

	warnAddText = "Тшш, поаккуратней с сообщениями\nУчастник имеет {0}/{1} предупреждений"
	warnRemText = "Сняты все предупреждения"
	banText = "Ой, отлетел челик"
	muteText = "Тшш, помолчи"
	
	settingsTitle = "Настройки"
	settingsWarnText = "Количество предупреждений: "
	settingsLangText = "Язык"
	backButtonText = "Назад"
	settingsChatDefaultsText = "Дефолтные настройки чата"
	settingsAdminDefaultsText = "Дефолт права админа"

	defaultchatSendMessage = "Отправка сообщений"
	defaultchatSendMedia = "Медиа"
	defaultchatSendPolls = "Голосование"
	defaultchatSendOther = "Стикеры/GIF"
	defaultchatAddPreview = "Превью"
	defaultchatChangeInfo = "Инфа чата"
	defaultchatCanInvite = "Приглашение"
	defaultchatPinMessages = "Закреп"

	defaultadminIsAnonymous = "Аноним"
	defaultadminCanChange = "Инфа чата"
	defaultadminCanDelete = "Удаление"
	defaultadminCanInvite = "Приглашение"
	defaultadminCanRestrict = "Бан"
	defaultadminCanPin = "Закреп"
	defaultadminCanPromote = "Новые админы"

class en_US:
	firstMessageText = "Hi chat!"
	helpCommandsText = "List of available commands: \n\n"
	helpNoCommandsText = "There are no commands! Try adding the first one with /addcom <command> <text>"
	commandNewText = "Added command !"
	commandRemoveText = "Deleted command !"
	promoteToAdminText = "Upped to Admin"
	promoteToUserText = "Demoted to User"

	aboutUserText = """<b>Info about</b> {0}\n<b>ID:</b> <code>{1}</code>\n<b>Messages:</b> {2}\n<b>Warns:</b> {3}/{4}"""
	langChange = "Language successfully changed to English"

	warnAddText = "You get a warning\nMember have {0}/{1} warnings"
	warnRemText = "Cleared all warnings"
	banText = "You have been banned from this chat"
	muteText = "Shut up"
	
	settingsTitle = "Settings"
	settingsWarnText = "Number of warns: "
	settingsLangText = "Language"
	backButtonText = "Back"
	

	settingsChatDefaultsText = "Дефолтные настройки чата"
	settingsAdminDefaultsText = "Дефолт права админа"

	defaultchatSendMessage = "Отправка сообщений"
	defaultchatSendMedia = "Медиа"
	defaultchatSendPolls = "Голосование"
	defaultchatSendOther = "Стикеры/GIF"
	defaultchatAddPreview = "Превью"
	defaultchatChangeInfo = "Инфа чата"
	defaultchatCanInvite = "Приглашение"
	defaultchatPinMessages = "Закреп"

	defaultadminIsAnonymous = "Аноним"
	defaultadminCanChange = "Инфа чата"
	defaultadminCanDelete = "Удаление"
	defaultadminCanInvite = "Приглашение"
	defaultadminCanRestrict = "Бан"
	defaultadminCanPin = "Закреп"
	defaultadminCanPromote = "Новые админы"

class uk_UA:	
	firstMessageText = "Привіт, чатику!"
	helpCommandsText = "Список доступних команд: \n\n"
	helpNoCommandsText = "Немає команд, додайте першу за допомогою /addcom <команда> <текст>"
	commandNewText = "Додана команда !"
	commandRemoveText = "Видалена команда !"
	promoteToAdminText = "Підвищено до Адміністратора"
	promoteToUserText = "Знижений до Користувача"

	aboutUserText = """<b>Информація про учасника</b> {0}\n<b>ID:<b> <code>{1}</code>\n<b>Всього повідомлень:</b> {2}\n<b>Попередження:</b> {3}/{4}"""
	langChange = "Мова успішно змінено на Українську"

	warnAddText = "Слідкуй за словами!\nВчасник має {0}/{1} попереджень"
	warnRemText = "Знято усі попередження"
	banText = "Бувай, козаче"
	muteText = "Помовчи"
	
	settingsTitle = "Налаштування"
	settingsWarnText = "кількість попереджень: "
	settingsLangText = "Мова"
	backButtonText = "Повернутися"


	settingsChatDefaultsText = "Дефолтные настройки чата"
	settingsAdminDefaultsText = "Дефолт права админа"

	defaultchatSendMessage = "Отправка сообщений"
	defaultchatSendMedia = ""
	defaultchatSendOther = ""
	defaultchatAddPreview = ""
	defaultadminIsAnonymous = ""
	defaultadminCanChange = ""
	defaultadminCanDelete = ""
	defaultadminCanInvite = ""
	defaultadminCanRestrict = ""
	defaultadminCanPin = ""
	defaultadminCanPromote = ""
